### ISSUE TITLE
Automatically close and then open applications.

### ISSUE THREAD

**Issue by sohate** [nielsmouthaan/ejectify-macos#23]
Automatically close and then open applications that prevent you from unmount an external hdd. Now, if certain applications work with an external hdd, then nothing happens. You have force unmount but it's unsafe. Can you add an option to let the user choose an application that should be auto-close and auto-open? Thanks!

**Comment by nielsmouthaan** [comment]
Thanks. I definitely understand and see its potential, but consider this out of scope for the moment.

**Comment by sohate** [comment]
Damn! I bought it already, but now it’s useless :( Still, thanks for good app.

On 30 Apr 2021, at 16:55, Niels Mouthaan ***@***.******@***.***>> wrote:



Thanks. I definitely understand and see its potential, but consider this out of scope for the moment.

**Comment by nielsmouthaan** [comment]
The thing is, I expect some issues with this feature. When a volume fails to unmount, it's likely because an app is using it. Stopping that app won't always help as that app will likely delay quitting in order to finalize its file process. Force quitting that app might corrupt (app) data and that's also what you don't want. Effectively what you're asking for is already possible with Ejectify. Enable _Force _unmount__ and it will unmount volumes even when apps are using those volumes. No need to quit te apps I expect.

**Comment by sohate** [comment]
Totally agree with that! But I’m afraid that unsafe eject corrupt my external hdd (not just files).

On 30 Apr 2021, at 17:02, Niels Mouthaan ***@***.******@***.***>> wrote:



The thing is, I expect some issues with this feature. When a volume fails to unmount, it's likely because an app is using it. Stopping that app won't always help as that app will likely delay quitting in order to finalize its file process. Force quitting that app might corrupt (app) data and that's also what you don't want. Effectively what you're asking for is already possible with Ejectify. Enable Force unmount and it will unmount volumes even when apps are using those volumes. No need to quit the apps I expect.

**Comment by nielsmouthaan** [comment]
Closing this issue as I consider this out-of-scope for Ejectify.
