### ISSUE TITLE
Settings are unclear (to me)

### ISSUE THREAD

**Issue by gagarine** [nielsmouthaan/ejectify-macos#41]
I don't fully understand the settings:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/164074/182019836-8c85e147-0b25-46b9-b978-ce5cdc1bba0e.png">

Do the display is turned off when my computer start sleeping? What is the safest option? Why are those options mutually exclusive?

Thanks!

**Comment by nielsmouthaan** [comment]
Yes, the display is turned off when your computer starts sleeping. But there might not be a screen saver so that one doesn't always run; it depends on your system configuration. I could make it a multi-selection menu, but it doesn't make sense to (un)mount multiple times. I have it configured to (un)mount when the display turns off.

**Comment by gagarine** [comment]
Thanks for the clarification!
